spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.ordersystem.model

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always

server:
  port: 8180